schema: workflow/2022.04
name: Customer Deal Flow Tracker
settings:
  error_notification: true
  lambda_memory: 512
  lambda_timeout: 750
steps:
- namespace: get_hubspot_contacts
  runtime: nodejs20.x
  uses: "./get_hubspot_contacts/entry.js"
  props:
    hubspot:
      authProvisionId: apn_b6hVBB6
    listId: '11'
    limit: 100
- namespace: search_email_threads
  runtime: nodejs20.x
  uses: "./search_email_threads/entry.js"
  props:
    gmail:
      authProvisionId: apn_vMhjLBk
    emailAddresses: "{{steps.get_hubspot_contacts.$return_value.emails}}"
- namespace: analyze_contact_status
  runtime: nodejs20.x
  uses: "./analyze_contact_status/entry.js"
  props:
    emailThreads: "{{steps.search_email_threads.$return_value}}"
    model: gpt-4o
- namespace: send_slack_notification
  runtime: nodejs20.x
  uses: slack-send-message-to-channel@0.0.4
  _props_cursor: dyp_aKUoLX1
  props:
    slack:
      authProvisionId: apn_kVhoygA
    conversation:
      __lv:
        label: 'Public channel: sales-briefer-ai'
        value: C09AFE3BQ0J
    thread_broadcast: false
    unfurl_links: false
    unfurl_media: false

